# Form implementation generated from reading ui file '.\src\ui\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(280, 140, 211, 221))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.BoatLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.BoatLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.BoatLayout.setContentsMargins(0, 0, 0, 0)
        self.BoatLayout.setObjectName("BoatLayout")
        self.BoatDesign = BoatWidget(self.verticalLayoutWidget_2)
        self.BoatDesign.setObjectName("BoatDesign")
        self.BoatLayout.addWidget(self.BoatDesign)
        self.CapControl = QtWidgets.QHBoxLayout()
        self.CapControl.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.CapControl.setSpacing(6)
        self.CapControl.setObjectName("CapControl")
        self.MinusButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.MinusButton.setObjectName("MinusButton")
        self.CapControl.addWidget(self.MinusButton)
        self.PlusButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.PlusButton.setObjectName("PlusButton")
        self.CapControl.addWidget(self.PlusButton)
        self.BoatLayout.addLayout(self.CapControl)
        self.SimulateButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.SimulateButton.setObjectName("SimulateButton")
        self.BoatLayout.addWidget(self.SimulateButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.MinusButton.setText(_translate("MainWindow", "-"))
        self.PlusButton.setText(_translate("MainWindow", "+"))
        self.SimulateButton.setText(_translate("MainWindow", "Simulate"))
from ui.BoatWidget import BoatWidget
